<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
  <meta charset="UTF-8">
  <title>Create</title>
  <link href="/css/main.css" rel="stylesheet">
</head>
<body>
<textarea id="code_snippet" placeholder="// write your code here"></textarea>
<br>
<label for="time_restriction">Time restriction:</label>
<input id="time_restriction" type="text" value="0"/>
<br>
<label for="views_restriction">Views restriction:</label>
<input id="views_restriction" type="text" value="0"/>
<button id="send_snippet" type="submit" onclick="send()">Submit</button>
<script src="js/send.js"></script>
</body>
</html>